version: '2'
networks:
  net_basic:
    external: true
services:
  node_service:
    image: node:8.10.0
    working_dir: /apps
    command:  bash -c "mkdir -p /apps && npm install && node enrollAdmin.js && node registerUser.js && node registerUser2.js && node registerUser3.js && node registerUser4.js && node registerUser5.js && node server.js"
    container_name: node
    expose: 
        - "8000"
    ports:
        - "8000:8000"
    volumes :
        - ./:/apps
    networks:
        - net_basic
    external_links:
        - peer0.org1.example.com
        - orderer.example.com
        - ca.example.com